ohh

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,14 +1,23 @@
 #!/usr/bin/env bash
+# a bash script that translates a file from client to server
 
-#+    The path to the file to be transferred.
-#+    The IP of the server to transfer the file to.
-#+    The username that scp connects with.
-#+    The path to the SSH private key that scp uses.
+if [ "$#" -lt 4 ]; then
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
+fi
 
+# Assign the parameters to variables
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
 
-if [ $# -lt 4 ]
-then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# Use scp to transfer the file to the server
+scp -o StrictHostKeyChecking=no -i $path_to_ssh_key $path_to_file $username@$ip:~
+
+# Check the exit status of the scp command
+if [ $? -eq 0 ]; then
+  echo "File transferred successfully."
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+  echo "File transfer failed."
 fi
